[build]
  publish = "."

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, x-admin-pin"
    Access-Control-Allow-Methods = "GET,POST,PUT,PATCH,DELETE,OPTIONS"

[[edge_functions]]
path = "/api/db"
function = "db"
